[package]
name = "cowrpc"
version = "0.4.0"
license = "MIT/Apache-2.0"
authors = ["François Dubois <fdubois@devolutions.net>, Richer Archambault <rarchambault@devolutions.net>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
bufstream = "0.1.3"
rmp = "0.8.7"
mio = "0.6.13"
mio-extras = "2.0"
log = "0.4.1"
env_logger = "0.5.3"
bytes = "0.4.4"
dns-lookup = "0.9.0"
native-tls = "0.2"
tungstenite = "0.6"
timer = "0.2"
time = "0.1"
url = "1.7"
rand = "0.4"
mouscache = "^0.5.4"
mouscache_derive = "0.4"
futures = "0.1.29"
futures_03 = { package = "futures", version = "0.3", features = ["compat"] }
parking_lot = "0.6"
tokio = { version = "0.2.11", features = ["full"] }
tokio-tcp = "0.1.2"
tls-api = { git = "https://github.com/devolutions/rust-tls-api", branch = "wayk" }
tls-api-native-tls = { git = "https://github.com/devolutions/rust-tls-api", branch = "wayk" }

[dev-dependencies]
cowrpc_derive = {path = "../cowrpc_derive"}