[package]
name = "cowrpc_derive"
version = "0.1.0"
edition = "2018"
license = "MIT/Apache-2.0"
authors = ["François Dubois <fdubois@devolutions.net>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.5"
proc-macro2 = "0.3"


[dependencies.syn]
version = "0.13"
features = ["full"]
